SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8;
CREATE DATABASE IF NOT EXISTS MATRICULA;
USE MATRICULA;

-- 1. TABLA ALUMNOS
DROP TABLE IF EXISTS Alumnos;
CREATE TABLE Alumnos (
    ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
    DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    EDAD INT NOT NULL,
    GENERO CHAR(1) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    CELULAR CHAR(9) NOT NULL,
    CORREO VARCHAR(80) UNIQUE NOT NULL,
    NOMBRE_APODERADO VARCHAR(50) NOT NULL,
    CELULAR_APODERADO CHAR(9) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(20) DEFAULT 'Activo',
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABLA AULA
DROP TABLE IF EXISTS Aula;
CREATE TABLE Aula (
    ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
    NIVEL VARCHAR(30) NOT NULL,
    GRADO INT NOT NULL,
    SECCION CHAR(1) NOT NULL,
    VACANTES_TOTALES INT NOT NULL,
    VACANTES_DISPONIBLES INT NOT NULL
);

-- 3. TABLA CURSOS
DROP TABLE IF EXISTS Cursos;
CREATE TABLE Cursos (
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(100) NOT NULL,
    ID_AULA INT NOT NULL,
    DOCENTE VARCHAR(100) NOT NULL,
    HORAS_SEMANALES INT NOT NULL,
    CREDITOS INT NOT NULL,
    CONSTRAINT FK_Cursos_Aula FOREIGN KEY (ID_AULA) REFERENCES Aula(ID_AULA) ON DELETE CASCADE
);

-- 4. TABLA USUARIOS
DROP TABLE IF EXISTS Usuarios;
CREATE TABLE Usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    ESTADO TINYINT(1) DEFAULT 1
);

-- 5. TABLA RESERVA (Contrato/Matrícula de Aula)
DROP TABLE IF EXISTS Reserva;
CREATE TABLE Reserva (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_AULA INT NOT NULL,
    COD_PAGO VARCHAR(20) UNIQUE NOT NULL,
    FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE',
    CONSTRAINT FK_Reserva_Alumnos FOREIGN KEY (ID_ALUMNO) REFERENCES Alumnos(ID_ALUMNO) ON DELETE CASCADE,
    CONSTRAINT FK_Reserva_Aula FOREIGN KEY (ID_AULA) REFERENCES Aula(ID_AULA) ON DELETE CASCADE
);

-- 6. TABLA INSCRIPCION_CURSO (Inscripción independiente a Cursos)
DROP TABLE IF EXISTS Inscripcion_Curso;
-- Regla de negocio: Solo permitida si Alumnos.ESTADO = 'Activo'
CREATE TABLE Inscripcion_Curso (
    ID_INSCRIPCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_CURSO INT NOT NULL,
    FECHA_INSCRIPCION DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Inscripcion_Alumnos FOREIGN KEY (ID_ALUMNO) REFERENCES Alumnos(ID_ALUMNO) ON DELETE CASCADE,
    CONSTRAINT FK_Inscripcion_Cursos FOREIGN KEY (ID_CURSO) REFERENCES Cursos(ID_CURSO) ON DELETE CASCADE
);

-- SECCIÓN DE DATOS DE EJEMPLO

-- Insertar Usuarios (Contraseña: admin123)
INSERT INTO Usuarios (USERNAME, PASSWORD_HASH) VALUES 
('ADMIN', '$2y$10$KxGD1EZksyNWSZh774su4OIFKkjxHXelJZGFeJeb9CHMF5YR7EVj6'),
('ARIANA', '$2y$10$KxGD1EZksyNWSZh774su4OIFKkjxHXelJZGFeJeb9CHMF5YR7EVj6'),
('ANGEL', '$2y$10$KxGD1EZksyNWSZh774su4OIFKkjxHXelJZGFeJeb9CHMF5YR7EVj6');

-- Insertar Alumnos (5 registros)
INSERT INTO Alumnos (DNI_ALUMNO, NOMBRES, APELLIDO, FECHA_NACIMIENTO, EDAD, GENERO, DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO, CELULAR_APODERADO, USERNAME, PASSWORD_HASH, ESTADO) VALUES
('45789865', 'Pepito', 'Rosales', '2004-05-15', 20, 'M', 'Av. Perú 123', '986532877', 'pepito@gmail.com', 'Sonia Rosales', '986532789', 'Pepito', 'mundo', 'Activo'),
('72458963', 'Maria', 'Gomez', '2008-03-20', 16, 'F', 'Calle Los Alamos 456', '945871236', 'maria.gomez@hotmail.com', 'Carlos Gomez', '945871200', 'MariaG', 'pass123', 'Activo'),
('12345678', 'Juan', 'Perez', '2010-07-10', 14, 'M', 'Jr. Huascar 789', '912345678', 'juan.perez@gmail.com', 'Marta Perez', '912345600', 'JuanP', 'pass456', 'Inactivo'),
('87654321', 'Ana', 'Torres', '2005-11-25', 18, 'F', 'Av. Brasil 1010', '987654321', 'ana.torres@yahoo.com', 'Luis Torres', '987654300', 'AnaT', 'pass789', 'Activo'),
('44556677', 'Luis', 'Sosa', '2006-01-12', 18, 'M', 'Calle Arica 202', '944556677', 'luis.sosa@outlook.com', 'Elena Sosa', '944556600', 'LuisS', 'pass321', 'En Proceso');

-- Insertar Aulas (5 registros)
INSERT INTO Aula (NIVEL, GRADO, SECCION, VACANTES_TOTALES, VACANTES_DISPONIBLES) VALUES
('SECUNDARIA', 3, 'A', 30, 5),
('SECUNDARIA', 3, 'B', 30, 0),
('PRIMARIA', 1, 'A', 25, 25),
('PRIMARIA', 6, 'B', 30, 12),
('SECUNDARIA', 5, 'C', 35, 10);

-- Insertar Cursos (5 registros)
INSERT INTO Cursos (NOMBRE_CURSO, ID_AULA, DOCENTE, HORAS_SEMANALES, CREDITOS) VALUES
('Matemáticas', 1, 'Juan Pérez', 6, 4),
('Comunicación', 1, 'María Gómez', 5, 3),
('Ciencias', 2, 'Carlos Ruiz', 4, 3),
('Historia', 3, 'Ana Torres', 3, 2),
('Inglés', 4, 'Martha Stewart', 4, 3);

-- Insertar Reservas de ejemplo (Matrícula en Aula)
INSERT INTO Reserva (ID_ALUMNO, ID_AULA, COD_PAGO, ESTADO_PAGO) VALUES
(1, 1, 'PAG-001', 'PAGADO'),
(2, 1, 'PAG-002', 'PENDIENTE'),
(4, 5, 'PAG-003', 'PAGADO');

-- Insertar Inscripciones de Curso independientes
-- Solo para alumnos Activos (Pepito ID:1, Maria ID:2, Ana ID:4)
INSERT INTO Inscripcion_Curso (ID_ALUMNO, ID_CURSO) VALUES
(1, 1), -- Pepito en Matemáticas
(1, 2), -- Pepito en Comunicación
(2, 2), -- Maria en Comunicación
(4, 5); -- Ana en Inglés

-- Comprobación final
SELECT * FROM Alumnos;
SELECT * FROM Aula;
SELECT * FROM Cursos;
SELECT * FROM Usuarios;
SELECT * FROM Reserva;
SELECT * FROM Inscripcion_Curso;